'use client'

import { useState } from 'react'

type View = 'overview' | 'workspace' | 'clients' | 'onboarding' | 'decisions' | 'schedule'
type Status = 'Draft' | 'In Review' | 'Approved' | 'Final'
type AccessMode = 'landing' | 'internal' | 'client'

const capabilities = ['Strategy', 'Brand & Identity', 'Digital Product', 'Content & Campaigns', 'Growth & Performance', 'Motion & Film', 'Spatial & Experience', 'Partnerships']
const assets = [
  { name: 'Northstar brand platform', type: 'Strategy deck', capability: 'Brand & Identity', status: 'In Review', updated: 'Today, 10:42' },
  { name: 'Launch film — 30s cut', type: 'Video', capability: 'Content & Campaigns', status: 'Approved', updated: 'Yesterday' },
  { name: 'Growth sprint readout', type: 'Presentation', capability: 'Growth & Performance', status: 'Draft', updated: 'Sep 24' },
  { name: 'Product experience audit', type: 'Report', capability: 'Digital Product', status: 'Final', updated: 'Sep 21' },
]
const clients = [
  { name: 'Northstar Health', initials: 'NH', engagement: 'Active', project: 'Brand platform' },
  { name: 'Morrow Studio', initials: 'MS', engagement: 'Onboarding', project: 'Digital product sprint' },
  { name: 'Aster & Co.', initials: 'AC', engagement: 'Active', project: 'Growth campaign' },
  { name: 'Cedar Labs', initials: 'CL', engagement: 'Lead', project: 'Strategy exploration' },
]

export default function Home() {
  const [mode, setMode] = useState<AccessMode>('landing')
  const [view, setView] = useState<View>('overview')
  const [selectedClient, setSelectedClient] = useState('Northstar Health')
  const [statuses, setStatuses] = useState<Record<string, Status>>({})
  const [comment, setComment] = useState('')
  const [notice, setNotice] = useState('')
  const [clientStage, setClientStage] = useState<'intake' | 'dashboard'>('intake')
  const [theme, setTheme] = useState<'dark' | 'light'>('light')

  if (mode === 'landing') return <Landing theme={theme} onToggleTheme={() => setTheme(theme === 'dark' ? 'light' : 'dark')} onInternal={() => { setMode('internal'); setView('overview') }} onClient={() => { setMode('client'); setClientStage('intake') }} />
  if (mode === 'client' && clientStage === 'intake') return <ClientIntake onComplete={() => setClientStage('dashboard')} />

  const currentClient = clients.find((client) => client.name === selectedClient) || clients[0]
  const title = view === 'overview' ? 'Overview' : view === 'workspace' ? 'Client workspace' : view === 'clients' ? 'Clients' : view === 'onboarding' ? 'Onboarding' : view === 'decisions' ? 'Key decisions' : 'Schedule'
  const setRoute = (next: View) => { setView(next); setNotice('') }
  const approve = (name: string) => { setStatuses((current) => ({ ...current, [name]: 'Approved' })); setNotice('Asset approval recorded in the decision trail.') }
  const sendComment = (event: React.FormEvent) => { event.preventDefault(); if (!comment.trim()) return; setComment(''); setNotice('Comment added to the shared thread.') }

  return <main className={`appShell theme-${theme}`}>
    <aside className="sidebar">
      <button className="sideBrand" onClick={() => setMode('landing')}>SMOEDESIGN <span>HUB</span></button>
      <div className="workspaceSwitch"><span className="avatar">S</span><span><b>{mode === 'client' ? currentClient.name : 'SMOEDESIGN'}</b><small>{mode === 'client' ? 'Client workspace' : 'Internal workspace'}</small></span><span className="chevron">⌄</span></div>
      <nav className="sideNav" aria-label="Workspace navigation"><p className="navLabel">Workspace</p><Nav active={view === 'overview'} onClick={() => setRoute('overview')} icon="◈">Overview</Nav><Nav active={view === 'workspace'} onClick={() => setRoute('workspace')} icon="▣">Client workspace <i>4</i></Nav><Nav active={view === 'clients'} onClick={() => setRoute('clients')} icon="◎">Clients directory</Nav><p className="navLabel navGap">Operations</p><Nav active={view === 'onboarding'} onClick={() => setRoute('onboarding')} icon="↗">Onboarding <i>2</i></Nav><Nav active={view === 'decisions'} onClick={() => setRoute('decisions')} icon="☷">Key decisions <i>28</i></Nav><Nav active={view === 'schedule'} onClick={() => setRoute('schedule')} icon="◷">Schedule</Nav></nav>
      <div className="sideBottom"><div className="helpCard"><strong>Need a hand?</strong><span>Ask Hana about a project, client, or next step.</span><button onClick={() => setNotice('Hana is ready to help with your workspace.')}>Open assistant ↗</button></div><button className="profile"><span className="avatar avatarMuted">MO</span><span><b>Mo Smoe</b><small>Admin</small></span><span className="more">•••</span></button></div>
    </aside>
    <section className="content"><header className="topbar"><div className="crumb"><span>Workspace</span><b>/</b><strong>{title}</strong></div><div className="topActions"><button className="iconButton" aria-label="Search" onClick={() => setNotice('Search is ready — try a client or project name.')}>⌕</button><button className="iconButton" aria-label="Notifications" onClick={() => setNotice('You have 4 assets awaiting approval.')}>♢</button><button className="primaryButton" onClick={() => setRoute('onboarding')}>+ New client</button></div></header><div className="pageBody">
      {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss">×</button></div>}
      {view === 'overview' && <Overview setRoute={setRoute} />}
      {view === 'workspace' && <Workspace client={currentClient} selectedClient={selectedClient} setSelectedClient={setSelectedClient} statuses={statuses} approve={approve} comment={comment} setComment={setComment} sendComment={sendComment} mode={mode} />}
      {view === 'clients' && <Clients setRoute={setRoute} select={(name: string) => { setSelectedClient(name); setRoute('workspace') }} />}
      {view === 'onboarding' && <Onboarding />}
      {view === 'decisions' && <Decisions />}
      {view === 'schedule' && <Schedule />}
    </div></section>
  </main>
}

function Landing({ theme, onToggleTheme, onInternal, onClient }: { theme: 'dark' | 'light'; onToggleTheme: () => void; onInternal: () => void; onClient: () => void }) { return <main className={`landing theme-${theme}`}><div className="landingNav"><button className="sideBrand">SMOEDESIGN <span>HUB</span></button><div className="landingActions"><span className="availability"><b /> Studio systems for ambitious teams</span><button className="themeToggle" onClick={onToggleTheme} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}>{theme === 'dark' ? 'Light mode' : 'Dark mode'}</button></div></div><section className="landingHero"><p className="overline">The creative operating system</p><h1>Ideas into<br /><em>work.</em></h1><p className="landingCopy">One clear space for strategy, design, content, and the decisions that move your business forward.</p><div className="accessGrid"><button className="accessCard" onClick={onInternal}><span className="accessIcon">↗</span><span><b>Log in as Smoedesign</b><small>Internal workspace for your team</small></span><strong>→</strong></button><button className="accessCard" onClick={onClient}><span className="accessIcon hollow">○</span><span><b>Proceed as client</b><small>Review work, leave feedback, approve</small></span><strong>→</strong></button></div></section><footer className="landingFooter"><span>SMOEDESIGN / CREATIVE HUB</span><span>Strategy · Identity · Product · Culture</span><span>© 2025</span></footer></main> }
function Nav({ active, onClick, icon, children }: { active: boolean; onClick: () => void; icon: string; children: React.ReactNode }) { return <button className={`navItem ${active ? 'active' : ''}`} onClick={onClick}><span>{icon}</span>{children}</button> }
function Overview({ setRoute }: { setRoute: (view: View) => void }) { return <><div className="welcome"><div><p className="overline">Tuesday, September 30, 2025</p><h1>Good morning, Mo<span>.</span></h1><p className="lede">Here&apos;s what&apos;s moving across the hub today.</p></div><button className="secondaryButton" onClick={() => setRoute('workspace')}>View client workspace <span>↗</span></button></div><div className="statGrid"><Stat label="Active engagements" value="06" detail="+2 this month"/><Stat label="Awaiting approval" value="04" detail="2 need your attention" warm/><Stat label="Onboarding" value="02" detail="Next: Cedar Labs"/><Stat label="Decisions logged" value="28" detail="+6 this week"/></div><div className="dashboardGrid"><section className="panel wide"><PanelHead eyebrow="Across all projects" title="Project pulse" action="View all ↗" onClick={() => setRoute('workspace')} /><div className="table"><div className="tableRow tableHead"><span>Project</span><span>Owner</span><span>Status</span><span>Next milestone</span></div>{assets.map((asset, i) => <div className="tableRow" key={asset.name}><span className="projectName"><span className={`projectMark mark-${i}`}>{['N','L','G','P'][i]}</span><b>{asset.name}</b><small>{asset.capability}</small></span><span className="owner"><span className="tinyAvatar">{['AK','MS','JD','SL'][i]}</span>{['Ava Kim','Mo Smoe','Jon Diaz','Sana Lee'][i]}</span><Badge status={asset.status}/><span className="muted">{['Client review · today','Final edit · Oct 2','Internal review · Oct 1','Delivered · Sep 21'][i]}</span></div>)}</div></section><section className="panel decisions"><PanelHead eyebrow="Shared record" title="Key decisions" /><Decision title="Northstar tone of voice" detail="Approved by Maya Chen" time="Today, 09:18" /><Decision title="Homepage direction B" detail="Flagged for revision" time="Yesterday, 16:42" blue /><Decision title="Launch date confirmed" detail="Aster & Co. · Oct 14" time="Sep 28, 11:06" green /><button className="fullButton" onClick={() => setRoute('decisions')}>Open decision log ↗</button></section></div></> }
function Workspace({ client, selectedClient, setSelectedClient, statuses, approve, comment, setComment, sendComment, mode }: any) { return <><div className="workspaceHero"><div><p className="overline">{mode === 'client' ? 'Your project space' : 'Client-facing lens'}</p><h1>{mode === 'client' ? `Welcome, ${client.name.split(' ')[0]}.` : 'Client workspace'}</h1><p className="lede">A clear place for work, feedback, and decisions to move forward.</p></div><button className="secondaryButton">Share workspace ↗</button></div><div className="clientBar"><div className="clientLogo">{client.initials}</div><div><h2>{client.name}</h2><span>{client.project} · <b className="activeText">{client.engagement}</b></span></div><select value={selectedClient} onChange={(event) => setSelectedClient(event.target.value)} aria-label="Select client">{clients.map((item) => <option key={item.name}>{item.name}</option>)}</select></div><div className="capabilityStrip">{capabilities.map((capability, index) => <span key={capability} className={index === 1 ? 'selected' : ''}>{String(index + 1).padStart(2, '0')} {capability}</span>)}</div><div className="workspaceGrid"><section className="panel wide"><PanelHead eyebrow={`${client.name} · shared with client`} title="Project assets" action="Filter / Sort ↕" /><div className="assetList">{assets.map((asset) => { const status = statuses[asset.name] || asset.status; return <div className="assetRow" key={asset.name}><span className="fileIcon">▤</span><div className="assetInfo"><b>{asset.name}</b><span>{asset.type} · {asset.updated}</span></div><span className="capabilityTag">{asset.capability}</span><Badge status={status}/>{status === 'In Review' && <button className="approveButton" onClick={() => approve(asset.name)}>Approve</button>}</div>})}</div></section><section className="panel activity"><PanelHead eyebrow="Live thread" title="Feedback & decisions" /><div className="thread"><div className="threadItem"><span className="tinyAvatar peach">MC</span><div><b>Maya Chen <small>Today, 09:18</small></b><p>Love the warmer direction. Approved to move forward.</p></div></div><div className="threadItem"><span className="tinyAvatar blue">MO</span><div><b>Mo Smoe <small>Yesterday, 16:42</small></b><p>Added the final notes to the platform.</p></div></div></div><form className="commentBox" onSubmit={sendComment}><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Leave a comment..." aria-label="Leave a comment" /><button aria-label="Send comment">↗</button></form></section></div></> }
function Clients({ setRoute, select }: any) { return <><div className="welcome"><div><p className="overline">Relationship view</p><h1>Clients directory</h1><p className="lede">Every relationship, engagement, and next move in one place.</p></div><button className="primaryButton" onClick={() => setRoute('onboarding')}>+ Add client</button></div><div className="filterBar"><div className="searchBox">⌕ <input placeholder="Search clients" aria-label="Search clients" /></div><div className="filterPills"><button className="pillActive">All <span>12</span></button><button>Lead <span>3</span></button><button>Onboarding <span>2</span></button><button>Active <span>6</span></button><button>Closed <span>1</span></button></div></div><div className="clientCards">{clients.map((client) => <button className="clientCard" key={client.name} onClick={() => select(client.name)}><div className="clientCardTop"><span className="clientLogo">{client.initials}</span><Badge status={client.engagement} /></div><h2>{client.name}</h2><p>{client.project}</p><div className="clientCardBottom"><span>Last activity <b>{client.name === 'Northstar Health' ? 'Today' : 'Sep 28'}</b></span><span>↗</span></div></button>)}</div></> }
function ClientIntake({ onComplete }: { onComplete: () => void }) {
  const [submitted, setSubmitted] = useState(false)
  const [category, setCategory] = useState('Brand & Identity')
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); setTimeout(onComplete, 450) }
  return <main className="intakeShell"><header className="intakeNav"><button className="sideBrand" onClick={() => window.location.reload()}>SMOEDESIGN <span>HUB</span></button><span className="intakeStep">New client intake / 01</span></header><section className="intakeWrap"><div className="intakeIntro"><p className="overline">Welcome to the hub</p><h1>Let&apos;s make<br /><em>something matter.</em></h1><p>Tell us where you are headed. We&apos;ll connect the right specialists and shape a clear first step.</p></div><form className="intakeForm" onSubmit={submit}><div className="intakeProgress"><span className="active" /><span /><span /><span /></div><fieldset><legend>01 / Client info</legend><div className="fieldGrid"><label>Full name<input required name="name" placeholder="Your name" /></label><label>Work email<input required type="email" name="email" placeholder="you@company.com" /></label><label>Company<input required name="company" placeholder="Company name" /></label><label>Website <span className="optional">optional</span><input name="website" placeholder="company.com" /></label></div></fieldset><fieldset><legend>02 / Requirements category</legend><p className="fieldHint">What kind of support would move the work forward?</p><div className="categoryGrid">{capabilities.map((item) => <button type="button" key={item} className={category === item ? 'categoryChoice selected' : 'categoryChoice'} onClick={() => setCategory(item)}>{item}<span>{category === item ? '✓' : '↗'}</span></button>)}</div></fieldset><fieldset><legend>03 / Project brief</legend><label>What are you trying to achieve?<textarea required name="brief" placeholder="Share your goal, audience, timing, and what success looks like..." /></label></fieldset><fieldset><legend>04 / Upload context</legend><label className="uploadField"><input type="file" multiple /><span><b>Drop files here or browse</b><small>Briefs, decks, references, or anything useful · up to 25MB</small></span><strong>＋</strong></label></fieldset><div className="intakeFooter"><span>Usually takes 3–5 minutes</span><button className="primaryButton" type="submit" disabled={submitted}>{submitted ? 'Sending…' : 'Submit intake'} <span>→</span></button></div></form></section></main>
}

function Onboarding() { const steps = ['Qualify', 'Client info', 'Brief', 'Route & schedule', 'Kickoff confirmation']; return <><div className="workspaceHero"><div><p className="overline">Pipeline · new engagement</p><h1>Onboarding</h1><p className="lede">Move the right clients from first fit to first deliverable.</p></div><div className="progressCount"><b>02</b><span>in progress</span></div></div><div className="onboardingLayout"><section className="panel onboardingPanel"><PanelHead eyebrow="Morrow Studio" title="Digital product sprint" /><div className="stepper">{steps.map((step, index) => <div className={`step ${index < 2 ? 'done' : index === 2 ? 'current' : ''}`} key={step}><span>{index < 2 ? '✓' : index + 1}</span><b>{step}</b></div>)}</div><div className="qualify"><p className="overline">Step 03 · Collect brief</p><h2>What are they trying to build?</h2><p>Give the specialist team enough context to route the work well the first time.</p><textarea placeholder="Share the client&apos;s goal, audience, constraints, and what success looks like..." aria-label="Client brief" /><div className="formActions"><button className="secondaryButton">Save draft</button><button className="primaryButton">Continue to routing <span>→</span></button></div></div></section><aside className="panel onboardingAside"><p className="overline">Charter logic</p><h2>Route with confidence.</h2><p>Hana recommends a specialist team based on capability, scope, and timing.</p><div className="routeCard"><span className="routeIcon">◈</span><div><b>Recommended team</b><strong>Strategy + Digital Product</strong><small>Based on current brief</small></div></div><div className="scheduleCard"><span>Next available kickoff</span><b>Thu, Oct 2 · 11:00 AM</b><small>45 min · with Ava Kim</small></div></aside></div></> }
function Decisions() { return <><div className="welcome"><div><p className="overline">Shared record</p><h1>Key decisions</h1><p className="lede">A timestamped trail of approvals, feedback, and the calls that keep work moving.</p></div></div><section className="panel decisionPage">{['Northstar tone of voice','Homepage direction B','Launch date confirmed','Audience definition'].map((item, i) => <div className="decisionRow" key={item}><span className={`decisionDot ${i === 1 ? 'blueDot' : ''}`} /><div><b>{item}</b><p>{i === 1 ? 'Flagged for revision' : 'Approved by ' + ['Maya Chen', 'Mo Smoe', 'Aster & Co.', 'Morrow Studio'][i]}</p></div><small>{['Today, 09:18','Yesterday, 16:42','Sep 28, 11:06','Sep 26, 14:20'][i]}</small></div>)}</section></> }
function Schedule() { return <><div className="welcome"><div><p className="overline">Operations</p><h1>Schedule</h1><p className="lede">The next moments that matter across every engagement.</p></div><button className="primaryButton">+ Add event</button></div><section className="panel schedulePage">{['Kickoff · Morrow Studio','Review · Northstar Health','Final delivery · Aster & Co.'].map((item, i) => <div className="scheduleRow" key={item}><span className="dateBox"><b>{['02','03','14'][i]}</b><small>OCT</small></span><div><b>{item}</b><p>{['Thu · 11:00 AM · 45 min','Fri · 2:30 PM · 60 min','Tue · All day'][i]}</p></div><Badge status={i === 0 ? 'Onboarding' : 'Active'} /></div>)}</section></> }
function PanelHead({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action?: string; onClick?: () => void }) { return <div className="panelHeader"><div><p className="overline">{eyebrow}</p><h2>{title}</h2></div>{action && <button className="textButton" onClick={onClick}>{action}</button>}</div> }
function Decision({ title, detail, time, blue, green }: { title: string; detail: string; time: string; blue?: boolean; green?: boolean }) { return <div className="decision"><span className={`decisionDot ${blue ? 'blueDot' : green ? 'greenDot' : ''}`} /><div><b>{title}</b><p>{detail}</p><small>{time}</small></div></div> }
function Stat({ label, value, detail, warm }: { label: string; value: string; detail: string; warm?: boolean }) { return <div className="stat"><p>{label}</p><strong>{value}</strong><span className={`trend ${warm ? 'warm' : ''}`}>{warm ? '! ' : '↗ '}{detail}</span></div> }
function Badge({ status }: { status: string }) { return <span className={`badge badge-${status.toLowerCase().replaceAll(' ', '-')}`}>{status}</span> }
